AWSTemplateFormatVersion: 2010-09-09
Parameters:
  Name:
    Type: String
    Default: canarysubnetgroup

Mappings:
  RegionMap:
    ap-south-1:
      SubnetIds: ["subnet-2d38c646", "subnet-3f391673", "subnet-05c8be7e"]
    ap-northeast-1:
      SubnetIds: ["subnet-905bd6d8", "subnet-7e33cc24", "subnet-6c148047"]
    eu-west-1:
      SubnetIds: ["subnet-c128039b", "subnet-0004ea79", "subnet-26f40d6d"]
    sa-east-1:
      SubnetIds: ["subnet-a8ace9ce","subnet-fc8cf7b5","subnet-0e4b0855"]
    us-east-1:
      SubnetIds: ["subnet-a1728ced", "subnet-abcfe4f4", "subnet-066a5e27"]
    us-west-2:
      SubnetIds: ["subnet-20f0766a", "subnet-95b1d4ed", "subnet-483e4915"]

Resources:
  SubnetGroup01:
    Type: AWS::MemoryDB::SubnetGroup
    Metadata:
      Comment: MemoryDB SubnetGroup 01
    Properties:
      SubnetGroupName: !Ref Name
      Description: MemoryDB CFN canary subnet group
      SubnetIds: !FindInMap [RegionMap, !Ref "AWS::Region", SubnetIds]
      Tags:
      -  Key: service
         Value: memorydb
      -  Key: resource
         Value: subnet-group
