AWSTemplateFormatVersion: 2010-09-09
Parameters:
  Name:
    Type: String
    Default: canarysubnetgroup

Resources:
  SubnetGroup01:
    Type: AWS::MemoryDB::SubnetGroup
    Metadata:
      Comment: MemoryDB SubnetGroup 01
    Properties:
      SubnetGroupName: !Ref Name
      Description: MemoryDB CFN canary subnet group
      SubnetIds: ["subnet-a8ace9ce","subnet-fc8cf7b5","subnet-0e4b0855"]
      Tags:
      -  Key: service
         Value: memorydb
      -  Key: resource
         Value: subnet-group
