AWSTemplateFormatVersion: 2010-09-09
Parameters:
  Name:
    Type: String
    Default: canaryNonDataTieringCluster

Resources:
  Cluster01:
    Type: AWS::MemoryDB::Cluster
    Metadata:
      Comment: MemoryDB Non Data Tiering Cluster 01
    Properties:
      ClusterName: !Ref Name
      Description: MemoryDB Non Data Tiering CFN canary cluster
      NodeType: db.r6g.xlarge
      NumShards: 1
      NumReplicasPerShard: 1
      ACLName: open-access
      Tags:
      -  Key: service
         Value: memorydb
      -  Key: resource
         Value: cluster
