AWSTemplateFormatVersion: 2010-09-09
Parameters:
  Name:
    Type: String
    Default: canarycluster

Resources:
  Cluster01:
    Type: AWS::MemoryDB::Cluster
    Metadata:
      Comment: MemoryDB Cluster 01
    Properties:
      ClusterName: !Ref Name
      Description: MemoryDB CFN canary cluster
      NodeType: db.r6g.large
      NumShards: 1
      NumReplicasPerShard: 1
      ACLName: open-access
      Tags:
      -  Key: service
         Value: memorydb
      -  Key: resource
         Value: cluster
